base_model_path: '/data/cx/ysp/aigc-smart-painter/models/stable-diffusion-v1-5'
aux_model_path: '/data/cx/ysp/aigc-smart-painter/models/control-net-aux-models/Annotators'
device: 'cuda:2'
scheduler: 'PNDMScheduler' # aviliables are DDPMScheduler,DDIMScheduler,PNDMScheduler,LMSDiscreteScheduler,EulerDiscreteScheduler,EulerAncestralDiscreteScheduler,DPMSolverMultistepScheduler,
fp16: True
smart_mode: True  #是否自动进行长边等比例缩放 （SD只能比较好的生成512的图片）

# sam相关配置
sam:
  checkpoint: '/data/cx/ysp/aigc-smart-painter/models/sam/sam_vit_h_4b8939.pth'
  model_type: 'vit_h'
  device: 'cuda:2'
# SD框架基础模型配配置
pipes:
  txt2img:
    class_name: 'StableDiffusionPipeline'
    pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/stable-diffusion-v1-5'
    torch_dtype: 'torch.float16'
    device: 'cuda:2'
    scheduler: 'PNDMScheduler'
    mode: 'on'
  img2img:
    class_name: 'StableDiffusionImg2ImgPipeline'
    pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/stable-diffusion-v1-5'
    torch_dtype: 'torch.float16'
    device: 'cuda:2'
    scheduler: 'PNDMScheduler'
    mode: 'on'
  inpaint:
    class_name: 'StableDiffusionInpaintPipeline'
    pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/chilloutmix_NiPrunedFp32Fix'
    torch_dtype: 'torch.float16'
    device: 'cuda:2'
    scheduler: 'PNDMScheduler'
    mode: 'on'
  canny-control:
    class_name: 'StableDiffusionControlNetPipeline'
    pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/stable-diffusion-v1-5'
    controlnet:
        class_name: 'ControlNetModel'
        torch_dtype: 'torch.float16'
        pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/sd-controlnet-canny'
    torch_dtype: 'torch.float16'
    device: 'cuda:2'
    scheduler: 'UniPCMultistepScheduler'
    mode: 'on'
  openpose-control:
    class_name: 'StableDiffusionControlNetPipeline'
    pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/stable-diffusion-v1-5'
    controlnet:
      class_name: 'ControlNetModel'
      torch_dtype: 'torch.float16'
      pretrained_model_name_or_path: '/data/cx/ysp/aigc-smart-painter/models/sd-controlnet-openpose'
    torch_dtype: 'torch.float16'
    device: 'cuda:2'
    scheduler: 'UniPCMultistepScheduler'
    mode: 'on'



